#!/usr/bin/perl

sub ifconfig_reg{
	my @cmd =(`ifconfig`);
	my ($key, $value);
	my %ipReg;
	if(defined($value)){
		print "hello";
	}
	foreach (@cmd) {
		if(m/^(\w+)/){
			#print $1;
			$key=$1;
		}
		if(m/^\s+inet[^\d]+([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/){
			#print $1."\n";
			$value=$1;
		}
		if(defined($value)){
			$ipReg{$key}=$value;
			#print $key."  ";
			#print $value."\n";
			undef $value;
		}
	}
	return %ipReg;
}


my %ip = ifconfig_reg();
foreach $interface (sort keys %ip){
	print $interface . "=" . $ip{$interface} . "\n";
}
